### ISSUE TITLE
Perimordials is not defined

### ISSUE THREAD

**Issue by JunekCZ** [DesignRevision/shards-dashboard#24]
Hello!
I tried to run this beautiful dashboard but after `npm install` I tried to start `npm start` command and this happened:

```
> shards-dashboard@1.0.1 start
> gulp

fs.js:42
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:42:5
    at req_ (D:\Skola\Vysoka\projektak\dashboard\shards-dashboard\node_modules\natives\index.js:143:24)
    at Object.req [as require] (D:\Skola\Vysoka\projektak\dashboard\shards-dashboard\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (D:\Skola\Vysoka\projektak\dashboard\shards-dashboard\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)

```
My version of node is managed by **NVM** and I ran it with version 12.22.12 and latest (16.18.0).
Thank you in an advance for your replies!

**Comment by JunekCZ** [comment]
Okay, I found it out. I just downloaded the 4 year back old version of node - 6.8.0 with which I can run the dashboard!
